-- 회원가입양식 순서로 MEMBERS 테이블 순서변경 
--1. 백업테이블 생성
CREATE TABLE MEMBERS_BACK
AS SELECT MEM_NO, MEM_ID, MEM_NAME, MEM_PWD, EMAIL, MOBILE, 
          ZIPCODE, ADDRESS1, ADDRESS2, ADDREXTRA,GENDER,BIRTH_DATE,
          REG_DATE,POINT,STATUS,ADDRESS_NO,MEM_CATEGORY
FROM MEMBERS;

--2.MEMBERS 테이블삭제하기 
DROP TABLE MEMBERS;

--3. 백업테이블 이름 수정하기 
ALTER TABLE MEMBERS_BACK RENAME TO MEMBERS;

--4. 제약조건 PK 추가하기 
ALTER TABLE MEMBERS ADD CONSTRAINT PK_MEM_NO PRIMARY KEY(MEM_NO); 

--5.GENDER 사이즈 키우기 
ALTER TABLE MEMBERS MODIFY GENDER VARCHAR2(10);

--6-1. SEQ_MEM 마우스 오른쪽버튼 클릭해서 삭제한 뒤 

--6-2. 회원가입 시퀀스 1001번부터 다시 짜기 
CREATE SEQUENCE SEQ_MEM
START WITH 1001
MINVALUE 1
MAXVALUE 99999999999999999
INCREMENT BY 1
NOCACHE
NOCYCLE;
