
  CREATE TABLE "BROCCOLI"."ORDER" 
   (	"ORDER_NO" NUMBER NOT NULL ENABLE, 
	"MEM_NO" NUMBER NOT NULL ENABLE, 
	"DELIVER_NO" NUMBER NOT NULL ENABLE, 
	"ORDER_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ORDER_CONDITION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MEM_NAME" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ZIPCODE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ADDRESS1" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"ADDRESS2" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"MOBILE" VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	"RECEIVER" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"RECEIVER_PHONE" VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	"RECEIVE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DELIVERYFEE" NUMBER NOT NULL ENABLE, 
	"POINT_YN" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"PAYMENT" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"TOTAL_AMT" NUMBER NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"INVOICE_NO" NUMBER, 
	"DEL_YN" VARCHAR2(50 BYTE), 
	"DEL_COM" VARCHAR2(50 BYTE), 
	"DRIVER" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BROCCOLI"."ORDER"."ORDER_NO" IS '주문번호';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."MEM_NO" IS '회원번호';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."DELIVER_NO" IS '배송지번호';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."ORDER_DATE" IS '주문날짜';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."ORDER_CONDITION" IS '주문상태';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."MEM_NAME" IS '주문자명';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."ZIPCODE" IS '우편번호';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."ADDRESS1" IS '배송지주소';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."ADDRESS2" IS '상세주소';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."MOBILE" IS '연락처';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."RECEIVER" IS '수령인';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."RECEIVER_PHONE" IS '수령인연락처';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."RECEIVE" IS '수령방법';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."DELIVERYFEE" IS '배송비';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."POINT_YN" IS '적립금사용여부';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."PAYMENT" IS '결제방법';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."TOTAL_AMT" IS '결제금액';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."CATEGORY" IS '구분';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."INVOICE_NO" IS '운송장번호';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."DEL_YN" IS '배송상태';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."DEL_COM" IS '택배사';
   COMMENT ON COLUMN "BROCCOLI"."ORDER"."DRIVER" IS '배송기사명';




  CREATE TABLE "BROCCOLI"."ORDER_LIST" 
   (	"MEM_NO" NUMBER NOT NULL ENABLE, 
	"P_NO" NUMBER NOT NULL ENABLE, 
	"TOTAL_AMT" NUMBER NOT NULL ENABLE, 
	"P_PRICE" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"ORDER_NO" NUMBER, 
	"ORDER_CONDITION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "FK_MEMBERS_TO_ORDER_LIST_1" FOREIGN KEY ("MEM_NO")
	  REFERENCES "BROCCOLI"."MEMBERS" ("MEM_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BROCCOLI"."ORDER_LIST"."MEM_NO" IS '회원번호';
   COMMENT ON COLUMN "BROCCOLI"."ORDER_LIST"."P_NO" IS '상품번호';
   COMMENT ON COLUMN "BROCCOLI"."ORDER_LIST"."TOTAL_AMT" IS '총금액';
   COMMENT ON COLUMN "BROCCOLI"."ORDER_LIST"."P_PRICE" IS '상품가격';
   COMMENT ON COLUMN "BROCCOLI"."ORDER_LIST"."QUANTITY" IS '수량';
   COMMENT ON COLUMN "BROCCOLI"."ORDER_LIST"."ORDER_NO" IS '주문번호';
   COMMENT ON COLUMN "BROCCOLI"."ORDER_LIST"."ORDER_CONDITION" IS '주문상태';



  CREATE TABLE "BROCCOLI"."RETURN_EXCHANGE" 
   (	"MEM_NO" NUMBER NOT NULL ENABLE, 
	"ORDER_NO" NUMBER NOT NULL ENABLE, 
	"RETURN_REASON" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"RETURN_DETAIL_REASON" VARCHAR2(1000 BYTE), 
	"CLAIMANT_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CLAIMANT_PHONE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ZIPCODE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ADDRESS1" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"ADDRESS2" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"RETURN_WHETHER" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"DELIVER_SERVICE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"RETURN_DATE" DATE DEFAULT SYSDATE, 
	"INVOICE_NO" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."MEM_NO" IS '회원번호';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."ORDER_NO" IS '주문번호';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."RETURN_REASON" IS '사유선택';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."RETURN_DETAIL_REASON" IS '상세사유';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."CLAIMANT_NAME" IS '신청자명';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."CLAIMANT_PHONE" IS '연락처';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."ZIPCODE" IS '우편번호';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."ADDRESS1" IS '배송지주소';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."ADDRESS2" IS '상세주소';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."RETURN_WHETHER" IS '반품발송여부';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."DELIVER_SERVICE" IS '택배사';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."RETURN_DATE" IS '반품발송일';
   COMMENT ON COLUMN "BROCCOLI"."RETURN_EXCHANGE"."INVOICE_NO" IS '운송장번호';



  CREATE TABLE "BROCCOLI"."DELIVER_REGISTER" 
   (	"DELIVER_NO" NUMBER NOT NULL ENABLE, 
	"MEM_NO" NUMBER NOT NULL ENABLE, 
	"DELIVER_ADDRESS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DELIVER_ADDRESS2" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DELIVER_NAME" VARCHAR2(30 BYTE), 
	"RECEIVE_HOW" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"RECEIVER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"ADDRESS_YN" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "PK_DELIVER_REGISTER" PRIMARY KEY ("DELIVER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BROCCOLI"."DELIVER_REGISTER"."DELIVER_NO" IS '배송지번호';
   COMMENT ON COLUMN "BROCCOLI"."DELIVER_REGISTER"."MEM_NO" IS '회원번호';
   COMMENT ON COLUMN "BROCCOLI"."DELIVER_REGISTER"."DELIVER_ADDRESS" IS '배송지주소';
   COMMENT ON COLUMN "BROCCOLI"."DELIVER_REGISTER"."DELIVER_ADDRESS2" IS '상세주소';
   COMMENT ON COLUMN "BROCCOLI"."DELIVER_REGISTER"."DELIVER_NAME" IS '배송지명';
   COMMENT ON COLUMN "BROCCOLI"."DELIVER_REGISTER"."RECEIVE_HOW" IS '수령방법';
   COMMENT ON COLUMN "BROCCOLI"."DELIVER_REGISTER"."RECEIVER" IS '수령인';
   COMMENT ON COLUMN "BROCCOLI"."DELIVER_REGISTER"."ADDRESS_YN" IS '기본배송지여부';
